### ISSUE TITLE
The UI design for Staff Registration Page

### ISSUE THREAD

**Issue by jazlynyin** [wenshen7/BurzlyFoodOrderingSystem#1]
Is the staff registration page need to display the staff account ID?

**Comment by Kezin** [comment]
In my opinion, I think it is necessary to display it to allow the staff remember what's his staff ID.

**Comment by wenshen7** [comment]
But before they successful register, no ID will generate right?

**Comment by leonzly** [comment]
But we can make the system auto generate an id for staff don't you agree?

**Comment by jazlynyin** [comment]
Mean use coding to generate an ID? Not using database auto generate?

**Comment by mhyap999** [comment]
Use database to auto generate id, so the system wont get a duplicate id

**Comment by wenshen7** [comment]
Display the ID after successful register?

**Comment by jazlynyin** [comment]
I will try to do it.

**Comment by wenshen7** [comment]
Okay, that is all for today.
