### ISSUE TITLE
Delete data

### ISSUE THREAD

**Issue by jazlynyin** [wenshen7/BurzlyFoodOrderingSystem#10]
Should we really use the delete query to delete the data? But all data is very valuable right? Any opinion?

**Comment by mhyap999** [comment]
Some data no use should delete it, because keep too many data will waste database storage.

**Comment by leonzly** [comment]
In my opinion, it should have a delete function to allow user to delete the data.

**Comment by wenshen7** [comment]
I think if the user want to delete a staff mean the staff is no longer working at the restaurant. It is no point to keep the data of a staff who no working in the restaurant.

**Comment by jazlynyin** [comment]
So no need to keep to staff record after an user decided to delete a staff record?

**Comment by wenshen7** [comment]
Ya, just delete the entire specified staff data.

**Comment by jazlynyin** [comment]
Okay, thank you. I will use the delete query to implement the delete feature.
