### ISSUE TITLE
Can I develop the delete function together with add in a single form? I think that it is more convenient to maintain.

### ISSUE THREAD

**Issue by Kezin** [wenshen7/BurzlyFoodOrderingSystem#11]

**Comment by leonzly** [comment]
yes, I think it is a very good idea. I very agree with that.

**Comment by mhyap999** [comment]
Good idea, it can save the user memory load and have good UI flow

**Comment by jazlynyin** [comment]
It is greats, this allow the user of the system do stock maintenance easier.

**Comment by wenshen7** [comment]
It is good, with this idea, the staff no need to keep switching page to do stock maintenance.

**Comment by Kezin** [comment]
Ok, i'll do that perfectly. I think that's all for today.
