### ISSUE TITLE
2nd Sprint Review Meeting

### ISSUE THREAD

**Issue by wenshen7** [wenshen7/BurzlyFoodOrderingSystem#12]
Are you all satisfy with all the features done in this sprint?

**Comment by mhyap999** [comment]
Ya, all feature are good and user friendly.

**Comment by jazlynyin** [comment]
Overall, I think is very convenient to the users of this system.

**Comment by Kezin** [comment]
It's still acceptable since every function works well in the system.

**Comment by leonzly** [comment]
Overall all the features and function look well and I think user will satisfy with it.

**Comment by wenshen7** [comment]
Are you satisfy with the feature that implement by you?

**Comment by mhyap999** [comment]
Ya, I satisfy with those feature that I implemented for the user require.

**Comment by jazlynyin** [comment]
Not really, because the UI design done by me is not very nice, I'm unsatisfied with that.

**Comment by leonzly** [comment]
Not really too. I think all the feature in supplier should implement in page. So that, user can easy to use it

**Comment by Kezin** [comment]
yes, I have implemented all the user requirements in my feature

**Comment by wenshen7** [comment]
Will you feel very rush to implement your task?

**Comment by mhyap999** [comment]
Some task are rushing a bit but not all task all very rushing.

**Comment by Kezin** [comment]
Honestly, i do feel rush to complete my task in limited period of time. I hope we should have started this project earlier.

**Comment by leonzly** [comment]
I feel ok with it. Still enter my control

**Comment by jazlynyin** [comment]
I feel rush when implement some complex feature. It very sufficient time when implement some simple feature.

**Comment by wenshen7** [comment]
Okay, thank you for giving the feedback. We will do better next time. All of this will become our valuable experience.
