### ISSUE TITLE
Food display in food order page

### ISSUE THREAD

**Issue by wenshen7** [wenshen7/BurzlyFoodOrderingSystem#2]
Should we display the ordered food include the food picture in the food order page?

**Comment by jazlynyin** [comment]
I think that we can display the ordered food but do not include the food picture because it will slow down the performance of the system.

**Comment by Kezin** [comment]
I agree with you, Ms. Leow as the system need go to database and retrieve the appropriate image to display.

**Comment by mhyap999** [comment]
If the customer have a lot order, the image will resize into small pieces and it will complicated to view

**Comment by wenshen7** [comment]
Oh, I see. So the ordered food display in list format?

**Comment by leonzly** [comment]
In my opinion, I think should display the food picture because it can let the customer to know how the food look like. besides, some of customers do not know or cannot remember the food name, they can see the picture to recognize the food to make the order.

**Comment by mhyap999** [comment]
I not agree, because is staff use, so no need image

**Comment by mhyap999** [comment]
Did the order page need to add system time and date ?

**Comment by leonzly** [comment]
Is okay if it is use for staff, but if use for customer then should include in picture

**Comment by Kezin** [comment]
It's a good idea of adding system time and date as it can be print to the receipt too.

**Comment by jazlynyin** [comment]
I think shortcut keys should be provided so that experiences users can use it faster and conveniently.

**Comment by wenshen7** [comment]
Good idea, this will increase the quality of the system.

**Comment by mhyap999** [comment]
OK. I will implement it in the order page.

**Comment by wenshen7** [comment]
Okay, that is all for today.
