### ISSUE TITLE
The UI for supplier information page

### ISSUE THREAD

**Issue by leonzly** [wenshen7/BurzlyFoodOrderingSystem#3]
The search textbox can search for what type of information?

**Comment by jazlynyin** [comment]
Commonly, people will use the search function to search for specific details. If search supplier, it can show the specific personal information such as contact number or email address.

**Comment by wenshen7** [comment]
I agree what Yin Yin said. Other than that, you also can show the specific supplier supply what items. This allow restaurant staff more convenient when they want to re-stock.

**Comment by Kezin** [comment]
Don't forget about the company name too which is necessary.

**Comment by leonzly** [comment]
okay, I  will implement it

**Comment by jazlynyin** [comment]
The staff can use the company to search for specific supplier?

**Comment by Kezin** [comment]
No, you have misunderstand it, Ms Leow, I mean the supplier information should include the company name.

**Comment by jazlynyin** [comment]
Ya, I knew that. What I mean is, enter the company name in the search text box there to search for specific supplier. Or we only can use the supplier name to search for specific supplier?

**Comment by wenshen7** [comment]
I think use supplier ID to search also is a good way for search function.

**Comment by mhyap999** [comment]
The search function also can search Supplier ID right ?

**Comment by mhyap999** [comment]
So staff search the supplier ID efficiently in the textbox field it will give the staff more faster to get the supplier details.

**Comment by leonzly** [comment]
okay. how about we use both supplier ID and supplier Name??

**Comment by mhyap999** [comment]
One textbox field can search a lot of thing right ?

**Comment by leonzly** [comment]
ya, I mean use these two supplier ID and supplier Name as a searching things to search specific details of each supplier

**Comment by mhyap999** [comment]
Ok Good idea.

**Comment by leonzly** [comment]
okay. that's all for today. thank you
