### ISSUE TITLE
UI for Search Stock page

### ISSUE THREAD

**Issue by Kezin** [wenshen7/BurzlyFoodOrderingSystem#4]
Do i need to use grid view to view all the information of stock instead of using textbox, dropdown list and so on?

**Comment by leonzly** [comment]
In my opinion, I think i grid view is more suitable instead of others. Because it can view all the details of each stock.

**Comment by mhyap999** [comment]
Yes use grid view and table format can let staff to view the stock details easily.

**Comment by jazlynyin** [comment]
Grid view also included the sort function. It is suitable for display database information.

**Comment by wenshen7** [comment]
Grid view is good. Display only important information into it because is use grid view to display too much information will cause the UI become ugly.

**Comment by jazlynyin** [comment]
Ya, it will cause the grid view can't fully display on the screen.

**Comment by wenshen7** [comment]
Will you display the further details information in other screen?

**Comment by Kezin** [comment]
I don't think so, I would like to display all details in a single page.

**Comment by Kezin** [comment]
Since everyone agree to use grid view, so I will do it. I think that's all for today, thank you.
