### ISSUE TITLE
about staff information page

### ISSUE THREAD

**Issue by jazlynyin** [wenshen7/BurzlyFoodOrderingSystem#5]
Should I separate the staff registration page and staff information page?

**Comment by wenshen7** [comment]
Is it convenient to the users?

**Comment by jazlynyin** [comment]
I think nope, because this will caused increase of key stroke when using the system.

**Comment by leonzly** [comment]
I think you can make it in a same page.

**Comment by mhyap999** [comment]
Put in same page can make it simple for the user to use which follow the agile modeling value simplicity.

**Comment by Kezin** [comment]
Yes, I think it's good to make it in the same page too.

**Comment by wenshen7** [comment]
Ya, this can reuse the design in the staff registration page.

**Comment by jazlynyin** [comment]
Thank for the valuable opinion, I will implement it in this way. Thank you
