### ISSUE TITLE
Ordered page UI

### ISSUE THREAD

**Issue by wenshen7** [wenshen7/BurzlyFoodOrderingSystem#6]
The total price need to show in the big text field ?

**Comment by Kezin** [comment]
I think total price should use label instead of text field as it cannot be edited by users.

**Comment by leonzly** [comment]
ya. I agree with you too. we should use label rather than text field.  It can avoid users to make the changer

**Comment by jazlynyin** [comment]
If using text field, you can disable it when display the price.

**Comment by wenshen7** [comment]
Ya, if you want to use text field to display the price, you need to set the text field enable=false.

**Comment by mhyap999** [comment]
Ok , I agree that use label will be the best choice .

**Comment by mhyap999** [comment]
I will use label to implement that part.

**Comment by wenshen7** [comment]
Okay, thank you. This issue is created by mhyap999.
