### ISSUE TITLE
Ordered list design

### ISSUE THREAD

**Issue by mhyap999** [wenshen7/BurzlyFoodOrderingSystem#7]
The table need grid view or text field ?

**Comment by Kezin** [comment]
I think it's better to use grid view

**Comment by jazlynyin** [comment]
Grid view can display the ordered food list more tidy compare to text field because grid view almost same like table.

**Comment by leonzly** [comment]
grid View is the better choice

**Comment by mhyap999** [comment]
Grid view can let user to see the details easily.

**Comment by wenshen7** [comment]
Text field may cause the coding become longer because the to display data into each text field need code it one by one. This will make the code become complex.

**Comment by mhyap999** [comment]
Ya add new data into the database also will be hard to insert it.

**Comment by jazlynyin** [comment]
Ya, I agree with what wenshen7 said. This will violate one of the agile principles which is simplicity. Do what is necessary, no more than necessary. Use the simple way to do it.

**Comment by mhyap999** [comment]
Thank all for  your valuable opinions. Helps me a lot. Thank you all. Have a good weekend :)
