### ISSUE TITLE
Sprint Review Meeting

### ISSUE THREAD

**Issue by wenshen7** [wenshen7/BurzlyFoodOrderingSystem#8]
Are you all satisfy with all the features ?

**Comment by jazlynyin** [comment]
The staff registration browse picture feature is user friendly because it is consistent with other software system.

**Comment by leonzly** [comment]
I feel satisfy with all the feature in supplier module especially in search supplier part, user can easy to search and view all the details inside the grids view.

**Comment by Kezin** [comment]
The search stock module is great as it is simple and provides all useful information for end user.

**Comment by mhyap999** [comment]
The order page feature are user friendly and all are clearly state what the customer have ordered in the order list.

**Comment by wenshen7** [comment]
Oh, Okay, Is that anyone have idea to add new user story into backlog?

**Comment by jazlynyin** [comment]
I think a delete feature can include to the backlog for staff.

**Comment by mhyap999** [comment]
A membership feature can include to the backlog for customer have 10 % privilege discount.

**Comment by Kezin** [comment]
I think delete stock information should be develop to allow admin to delete stock which is not available any more.

**Comment by leonzly** [comment]
I think delete supplier should be develop also because it can allow admin to delete supplier which is not available any more.

**Comment by wenshen7** [comment]
Okay, all the suggestion will add to the product backlog. That is all for today. Thank you
