### ISSUE TITLE
GST and Membership UI

### ISSUE THREAD

**Issue by mhyap999** [wenshen7/BurzlyFoodOrderingSystem#9]
GST and membership need to display 6% and 10% of total or just display the Grand total ?

**Comment by wenshen7** [comment]
I think need to display the 6% and 10% because if no display users may confuse about the calculation.

**Comment by jazlynyin** [comment]
The 6% is tax which must let the users know how much is it. The 10% is discount also need to show out how much has been deducted.

**Comment by wenshen7** [comment]
hey hey hey hey

**Comment by wenshen7** [comment]
heyhey hey hey

**Comment by leonzly** [comment]
I agree with Yin yin and wen shen. it let the user know how much it charge for GST and the discount

**Comment by Kezin** [comment]
I agree with all of you that it is necessary to display the 6% GST and 10% discount for customers to understand the money they have paid is not being cheated.

**Comment by mhyap999** [comment]
Thank all for your valuable opinions. Helps me a lot. Thank you all.  I will implement those feature.
I think that all for today. Have a nice day.
